apiVersion: v1
kind: ReplicationController
metadata:
  name: rancher
  namespace: cattle-system
  labels:
    name: rancher 
    app: rancherapp
spec:
  replicas: 1
  selector:
    name: rancher
    app: rancherapp
  template:
    metadata:
      labels:
        name: rancher
        app: rancherapp
    spec:
      containers:
      - name: rancher
        image: rancher/server:preview
        ports:
        - containerPort: 80
        - containerPort: 443
