apiVersion: v1
kind: Service
metadata:
  name: rancherexpose
  namespace: cattle-system
  labels:
    app: rancherapp
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 31222
  ports:
    - port: 443
      nodePort: 31221
  selector:
    app: rancherapp
  

